_ABSTRACT_NODES = [u'abstractBaseCreate', u'abstractBaseNurbsConversion', u'adskAssetInstanceNode_TdependNode',
                   u'adskAssetInstanceNode_TdnTx2D', u'adskAssetInstanceNode_TlightShape', u'animBlendNodeBase',
                   u'animCurve', u'assembly', u'bakeSet', u'baseGeometryVarGroup', u'baseShadingSwitch', u'birailSrf',
                   u'blend', u'boundaryBase', u'cacheBase', u'clientDevice', u'constraint', u'controlPoint',
                   u'cteInterpolator', u'curveFromMesh', u'curveFromSubdiv', u'curveFromSurface', u'curveNormalizer',
                   u'curveRange', u'curveShape', u'dagNode', u'deformFunc', u'deformableShape', u'dimensionShape',
                   u'dynBase', u'entity', u'field', u'filter', u'geometryShape', u'groundPlane', u'hwShader',
                   u'ikSolver', u'imageSource', u'light', u'makeCircularArc', u'manip2D', u'manip3D', u'nBase', u'node',
                   u'nonAmbientLightShapeNode', u'nonExtendedLightShapeNode', u'nurbsDimShape', u'orthoGrid',
                   u'parentTessellate', u'pfxGeometry', u'plane', u'polyBase', u'polyCreator', u'polyModifier',
                   u'polyModifierUV', u'polyModifierWorld', u'polyPrimitive', u'primitive', u'reflect', u'renderLight',
                   u'resultCurve', u'revolvedPrimitive', u'shadingDependNode', u'shape', u'subdBase', u'subdModifier',
                   u'subdModifierUV', u'subdModifierWorld', u'surfaceShape', u'texBaseDeformManip', u'texture2d',
                   u'texture3d', u'textureEnv', u'threadedDevice', u'writeToFrameBuffer']


_CONCRETE_NODES = [u'AISEnvFacade', u'AlembicNode', u'ComputeGlobal', u'ComputeLocal', u'CustomRigDefaultMappingNode',
                   u'CustomRigRetargeterNode', u'HIKCharacterNode', u'HIKCharacterStateClient', u'HIKControlSetNode',
                   u'HIKEffector2State', u'HIKEffectorFromCharacter', u'HIKFK2State', u'HIKPinning2State',
                   u'HIKProperty2State', u'HIKRetargeterNode', u'HIKSK2State', u'HIKSkeletonGeneratorNode',
                   u'HIKSolverNode', u'HIKState2Effector', u'HIKState2FK', u'HIKState2GlobalSK', u'HIKState2SK',
                   u'ShaderfxShader', u'StingrayPBS', u'Unfold3DOptimize', u'Unfold3DUnfold',
                   u'aboutToSetValueTestNode', u'addDoubleLinear', u'addMatrix', u'adskMaterial',
                   u'adskPrepareRenderGlobals', u'aimConstraint', u'airField', u'airManip', u'alignCurve',
                   u'alignManip', u'alignSurface', u'ambientLight', u'angleBetween', u'angleDimension', u'animBlend',
                   u'animBlendInOut', u'animBlendNodeAdditive', u'animBlendNodeAdditiveDA', u'animBlendNodeAdditiveDL',
                   u'animBlendNodeAdditiveF', u'animBlendNodeAdditiveFA', u'animBlendNodeAdditiveFL',
                   u'animBlendNodeAdditiveI16', u'animBlendNodeAdditiveI32', u'animBlendNodeAdditiveRotation',
                   u'animBlendNodeAdditiveScale', u'animBlendNodeBoolean', u'animBlendNodeEnum', u'animBlendNodeTime',
                   u'animClip', u'animCurveTA', u'animCurveTL', u'animCurveTT', u'animCurveTU', u'animCurveUA',
                   u'animCurveUL', u'animCurveUT', u'animCurveUU', u'animLayer', u'animLayerClip',
                   u'animLayerClipContainer', u'animLayerClipRoster', u'animLayerClipRotation', u'animLayerClipSingle',
                   u'animLayerClipTRS', u'anisotropic', u'annotationShape', u'apfEntityNode', u'apfFileNode',
                   u'arcLengthDimension', u'areaLight', u'arrayMapper', u'arrowManip', u'assemblyDefinition',
                   u'assemblyReference', u'attachCurve', u'attachSurface', u'attrHierarchyTest', u'audio', u'avgCurves',
                   u'avgCurvesManip', u'avgNurbsSurfacePoints', u'avgSurfacePoints', u'axesActionManip',
                   u'ballProjManip', u'barnDoorManip', u'baseLattice', u'bevel', u'bevelManip', u'bevelPlus',
                   u'bezierCurve', u'bezierCurveToNurbs', u'bifrostAeroMaterial', u'bifrostAttrNotifier',
                   u'bifrostContainer', u'bifrostFoamMaterial', u'bifrostLiquidMaterial', u'bifrostShape',
                   u'blendColorSets', u'blendColors', u'blendDevice', u'blendManip', u'blendShape', u'blendTwoAttr',
                   u'blendWeighted', u'blindDataTemplate', u'blinn', u'boneLattice', u'boolean', u'boundary',
                   u'brownian', u'brush', u'bulge', u'bump2d', u'bump3d', u'buttonManip', u'cMuscleCreator',
                   u'cMuscleDebug', u'cMuscleDirection', u'cMuscleDisplace', u'cMuscleDisplay', u'cMuscleFalloff',
                   u'cMuscleKeepOut', u'cMuscleMultiCollide', u'cMuscleObject', u'cMuscleRelative', u'cMuscleShader',
                   u'cMuscleSmartCollide', u'cMuscleSmartConstraint', u'cMuscleSpline', u'cMuscleSplineDeformer',
                   u'cMuscleStretch', u'cMuscleSurfAttach', u'cMuscleSystem', u'cacheBlend', u'cacheFile',
                   u'caddyManip', u'caddyManipBase', u'camera', u'cameraManip', u'cameraPlaneManip', u'cameraSet',
                   u'cameraView', u'centerManip', u'character', u'characterMap', u'characterOffset', u'checker',
                   u'choice', u'chooser', u'circleManip', u'circleSweepManip', u'clamp', u'clipGhostShape',
                   u'clipLibrary', u'clipScheduler', u'clipToGhostData', u'closeCurve', u'closeSurface',
                   u'closestPointOnMesh', u'closestPointOnSurface', u'cloth', u'cloud', u'cluster',
                   u'clusterFlexorShape', u'clusterHandle', u'coiManip', u'collisionModel', u'colorManagementGlobals',
                   u'colorProfile', u'compactPlugArrayTest', u'componentManip', u'composeMatrix',
                   u'concentricProjManip', u'condition', u'container', u'containerBase', u'contourProjManip',
                   u'contrast', u'controller', u'copyColorSet', u'copyUVSet', u'cpManip', u'crater', u'creaseSet',
                   u'createBPManip', u'createCVManip', u'createColorSet', u'createEPManip', u'createPtexUV',
                   u'createUVSet', u'cte', u'cteAnimSource', u'cteCurveVisualizer', u'cteInterpolatorRotation',
                   u'cteInterpolatorSingle', u'cteInterpolatorTRS', u'cteRoster', u'cteTracks', u'cubeManip',
                   u'cubicProjManip', u'curveEdManip', u'curveFromMeshCoM', u'curveFromMeshEdge',
                   u'curveFromSubdivEdge', u'curveFromSubdivFace', u'curveFromSurfaceBnd', u'curveFromSurfaceCoS',
                   u'curveFromSurfaceIso', u'curveInfo', u'curveIntersect', u'curveNormalizerAngle',
                   u'curveNormalizerLinear', u'curveSegmentManip', u'curveVarGroup', u'cylindricalProjManip',
                   u'dagContainer', u'dagPose', u'dataBlockTest', u'decomposeMatrix', u'defaultLightList',
                   u'defaultRenderUtilityList', u'defaultRenderingList', u'defaultShaderList', u'defaultTextureList',
                   u'deformBend', u'deformBendManip', u'deformFlare', u'deformFlareManip', u'deformSine',
                   u'deformSineManip', u'deformSquash', u'deformSquashManip', u'deformTwist', u'deformTwistManip',
                   u'deformWave', u'deformWaveManip', u'deleteColorSet', u'deleteComponent', u'deleteUVSet',
                   u'deltaMush', u'detachCurve', u'detachSurface', u'directedDisc', u'directionManip',
                   u'directionalLight', u'discManip', u'diskCache', u'displacementShader', u'displayLayer',
                   u'displayLayerManager', u'distanceBetween', u'distanceDimShape', u'distanceManip', u'dof',
                   u'dofManip', u'doubleShadingSwitch', u'dpBirailSrf', u'dragField', u'dropoffLocator',
                   u'dropoffManip', u'dynAttenuationManip', u'dynController', u'dynGlobals', u'dynHolder',
                   u'dynSpreadManip', u'dynamicConstraint', u'editMetadata', u'editsManager', u'emitterManip',
                   u'enableManip', u'envBall', u'envChrome', u'envCube', u'envFacade', u'envFog', u'envSky',
                   u'envSphere', u'environmentFog', u'eulerToQuat', u'explodeNurbsShell', u'expression', u'extendCurve',
                   u'extendCurveDistanceManip', u'extendSurface', u'extendSurfaceDistanceManip', u'extrude',
                   u'extrudeManip', u'facade', u'ffBlendSrf', u'ffBlendSrfObsolete', u'ffFilletSrf', u'ffd',
                   u'fieldManip', u'fieldsManip', u'file', u'filletCurve', u'filterClosestSample', u'filterEuler',
                   u'filterResample', u'filterSimplify', u'fitBspline', u'flexorShape', u'flow', u'fluidEmitter',
                   u'fluidShape', u'fluidSliceManip', u'fluidTexture2D', u'fluidTexture3D', u'follicle',
                   u'forceUpdateManip', u'fosterParent', u'fourByFourMatrix', u'fractal', u'frameCache',
                   u'freePointManip', u'freePointTriadManip', u'gameFbxExporter', u'gammaCorrect', u'geoConnectable',
                   u'geoConnector', u'geomBind', u'geometryConstraint', u'geometryFilter', u'geometryOnLineManip',
                   u'geometryVarGroup', u'globalCacheControl', u'globalStitch', u'gpuCache', u'granite',
                   u'gravityField', u'greasePencilSequence', u'greasePlane', u'greasePlaneRenderShape', u'grid',
                   u'groupId', u'groupParts', u'guide', u'hairConstraint', u'hairSystem', u'hairTubeShader',
                   u'hardenPoint', u'hardwareRenderGlobals', u'hardwareRenderingGlobals', u'heightField',
                   u'hierarchyTestNode1', u'hierarchyTestNode2', u'hierarchyTestNode3', u'hikEffector', u'hikFKJoint',
                   u'hikFloorContactMarker', u'hikGroundPlane', u'hikHandle', u'hikIKEffector', u'hikSolver',
                   u'historySwitch', u'holdMatrix', u'hsvToRgb', u'hwReflectionMap', u'hwRenderGlobals',
                   u'hyperGraphInfo', u'hyperLayout', u'hyperView', u'igBrushManip', u'igmDescription', u'ik2Bsolver',
                   u'ikEffector', u'ikHandle', u'ikMCsolver', u'ikPASolver', u'ikRPManip', u'ikRPsolver', u'ikSCsolver',
                   u'ikSplineManip', u'ikSplineSolver', u'ikSpringSolver', u'ikSystem', u'imagePlane', u'implicitBox',
                   u'implicitCone', u'implicitSphere', u'indexManip', u'insertKnotCurve', u'insertKnotSurface',
                   u'instancer', u'intersectSurface', u'inverseMatrix', u'isoparmManip', u'jiggle', u'joint',
                   u'jointCluster', u'jointClusterManip', u'jointFfd', u'jointLattice', u'jointTranslateManip',
                   u'keyframeRegionManip', u'keyingGroup', u'lambert', u'lattice', u'layeredShader', u'layeredTexture',
                   u'leastSquaresModifier', u'leather', u'lightFog', u'lightInfo', u'lightLinker', u'lightList',
                   u'lightManip', u'limitManip', u'lineManip', u'lineModifier', u'locator', u'lodGroup',
                   u'lodThresholds', u'loft', u'lookAt', u'luminance', u'makeGroup', u'makeIllustratorCurves',
                   u'makeNurbCircle', u'makeNurbCone', u'makeNurbCube', u'makeNurbCylinder', u'makeNurbPlane',
                   u'makeNurbSphere', u'makeNurbTorus', u'makeNurbsSquare', u'makeTextCurves',
                   u'makeThreePointCircularArc', u'makeThreePointCircularArcManip', u'makeTwoPointCircularArc',
                   u'makeTwoPointCircularArcManip', u'mandelbrot', u'mandelbrot3D', u'manip2DContainer',
                   u'manipContainer', u'marble', u'markerManip', u'materialFacade', u'materialInfo', u'membrane',
                   u'mentalrayTexture', u'mesh', u'meshVarGroup', u'motionPath', u'motionPathManip', u'motionTrail',
                   u'motionTrailShape', u'mountain', u'moveBezierHandleManip', u'moveVertexManip', u'movie',
                   u'mpBirailSrf', u'multDoubleLinear', u'multMatrix', u'multilisterLight', u'multiplyDivide', u'mute',
                   u'nCloth', u'nComponent', u'nParticle', u'nRigid', u'nearestPointOnCurve', u'network',
                   u'newtonField', u'newtonManip', u'nexManip', u'nodeGraphEditorBookmarkInfo',
                   u'nodeGraphEditorBookmarks', u'nodeGraphEditorInfo', u'noise', u'nonLinear', u'normalConstraint',
                   u'nucleus', u'nurbsCurve', u'nurbsCurveToBezier', u'nurbsSurface', u'nurbsTessellate',
                   u'nurbsToSubdiv', u'nurbsToSubdivProc', u'objectAttrFilter', u'objectBinFilter', u'objectFilter',
                   u'objectMultiFilter', u'objectNameFilter', u'objectRenderFilter', u'objectScriptFilter',
                   u'objectSet', u'objectTypeFilter', u'ocean', u'oceanShader', u'offsetCos', u'offsetCosManip',
                   u'offsetCurve', u'offsetCurveManip', u'offsetSurface', u'offsetSurfaceManip', u'oldBlindDataBase',
                   u'oldGeometryConstraint', u'oldNormalConstraint', u'oldTangentConstraint', u'opticalFX',
                   u'orientConstraint', u'orientationMarker', u'pairBlend', u'paramDimension', u'parentConstraint',
                   u'particle', u'particleAgeMapper', u'particleCloud', u'particleColorMapper', u'particleIncandMapper',
                   u'particleSamplerInfo', u'particleTranspMapper', u'partition', u'passContributionMap', u'passMatrix',
                   u'pfxHair', u'pfxToon', u'phong', u'phongE', u'pivot2dManip', u'pivotAndOrientManip',
                   u'place2dTexture', u'place3dTexture', u'planarProjManip', u'planarTrimSurface', u'plusMinusAverage',
                   u'pointConstraint', u'pointEmitter', u'pointLight', u'pointMatrixMult', u'pointOnCurveInfo',
                   u'pointOnCurveManip', u'pointOnLineManip', u'pointOnPolyConstraint', u'pointOnSurfManip',
                   u'pointOnSurfaceInfo', u'pointOnSurfaceManip', u'poleVectorConstraint', u'polyAppend',
                   u'polyAppendVertex', u'polyAutoProj', u'polyAutoProjManip', u'polyAverageVertex', u'polyBevel',
                   u'polyBevel2', u'polyBevel3', u'polyBlindData', u'polyBoolOp', u'polyBridgeEdge', u'polyCBoolOp',
                   u'polyCaddyManip', u'polyChipOff', u'polyCloseBorder', u'polyCollapseEdge', u'polyCollapseF',
                   u'polyColorDel', u'polyColorMod', u'polyColorPerVertex', u'polyCone', u'polyConnectComponents',
                   u'polyContourProj', u'polyCopyUV', u'polyCrease', u'polyCreaseEdge', u'polyCreateFace',
                   u'polyCreateToolManip', u'polyCube', u'polyCut', u'polyCutManip', u'polyCutManipContainer',
                   u'polyCylProj', u'polyCylinder', u'polyDelEdge', u'polyDelFacet', u'polyDelVertex',
                   u'polyDuplicateEdge', u'polyEdgeToCurve', u'polyEditEdgeFlow', u'polyExtrudeEdge',
                   u'polyExtrudeFace', u'polyExtrudeVertex', u'polyFlipEdge', u'polyFlipUV', u'polyHelix',
                   u'polyHoleFace', u'polyLayoutUV', u'polyMapCut', u'polyMapDel', u'polyMapSew', u'polyMapSewMove',
                   u'polyMappingManip', u'polyMergeEdge', u'polyMergeFace', u'polyMergeUV', u'polyMergeVert',
                   u'polyMergeVertsManip', u'polyMirror', u'polyModifierManip', u'polyModifierManipContainer',
                   u'polyMoveEdge', u'polyMoveFace', u'polyMoveFacetUV', u'polyMoveUV', u'polyMoveUVManip',
                   u'polyMoveVertex', u'polyMoveVertexManip', u'polyNormal', u'polyNormalPerVertex', u'polyNormalizeUV',
                   u'polyOptUvs', u'polyPassThru', u'polyPinUV', u'polyPipe', u'polyPlanarProj', u'polyPlane',
                   u'polyPlatonicSolid', u'polyPoke', u'polyPokeManip', u'polyPrimitiveMisc', u'polyPrism', u'polyProj',
                   u'polyProjManip', u'polyProjectCurve', u'polyPyramid', u'polyQuad', u'polyReduce', u'polyRemesh',
                   u'polySelectEditFeedbackManip', u'polySeparate', u'polySewEdge', u'polySmooth', u'polySmoothFace',
                   u'polySmoothProxy', u'polySoftEdge', u'polySphProj', u'polySphere', u'polySpinEdge', u'polySplit',
                   u'polySplitEdge', u'polySplitRing', u'polySplitToolManip1', u'polySplitVert',
                   u'polyStraightenUVBorder', u'polySubdEdge', u'polySubdFace', u'polyToSubdiv',
                   u'polyToolFeedbackManip', u'polyTorus', u'polyTransfer', u'polyTriangulate', u'polyTweak',
                   u'polyTweakUV', u'polyUVRectangle', u'polyUnite', u'polyVertexNormalManip', u'polyWedgeFace',
                   u'positionMarker', u'postProcessList', u'precompExport', u'projectCurve', u'projectTangent',
                   u'projectTangentManip', u'projection', u'projectionManip', u'projectionMultiManip',
                   u'projectionUVManip', u'propModManip', u'propMoveTriadManip', u'proxyManager', u'psdFileTex',
                   u'quadPtOnLineManip', u'quadShadingSwitch', u'quatAdd', u'quatConjugate', u'quatInvert',
                   u'quatNegate', u'quatNormalize', u'quatProd', u'quatSub', u'quatToEuler', u'radialField', u'ramp',
                   u'rampShader', u'rbfSrf', u'rbfSrfManip', u'rebuildCurve', u'rebuildSurface', u'record',
                   u'reference', u'remapColor', u'remapHsv', u'remapValue', u'renderBox', u'renderCone',
                   u'renderGlobals', u'renderGlobalsList', u'renderLayer', u'renderLayerManager', u'renderPass',
                   u'renderPassSet', u'renderQuality', u'renderRect', u'renderSphere', u'renderTarget',
                   u'renderedImageSource', u'resolution', u'resultCurveTimeToAngular', u'resultCurveTimeToLinear',
                   u'resultCurveTimeToTime', u'resultCurveTimeToUnitless', u'reverse', u'reverseCurve',
                   u'reverseCurveManip', u'reverseSurface', u'reverseSurfaceManip', u'revolve', u'revolveManip',
                   u'revolvedPrimitiveManip', u'rgbToHsv', u'rigidBody', u'rigidConstraint', u'rigidSolver', u'rock',
                   u'rotateHelper', u'rotateLimitsManip', u'rotateManip', u'rotateUV2dManip', u'roundConstantRadius',
                   u'roundConstantRadiusManip', u'roundRadiusCrvManip', u'roundRadiusManip', u'sampler', u'samplerInfo',
                   u'scaleConstraint', u'scaleLimitsManip', u'scaleManip', u'scaleUV2dManip',
                   u'screenAlignedCircleManip', u'script', u'scriptManip', u'sculpt', u'selectionListOperator',
                   u'sequenceManager', u'sequencer', u'setRange', u'shaderGlow', u'shadingEngine', u'shadingMap',
                   u'shellTessellate', u'shot', u'shrinkWrap', u'simpleTestNode', u'simpleVolumeShader',
                   u'singleShadingSwitch', u'sketchPlane', u'skinBinding', u'skinCluster', u'smear', u'smoothCurve',
                   u'smoothTangentSrf', u'snapUV2dManip', u'snapshot', u'snapshotShape', u'snow', u'softMod',
                   u'softModHandle', u'softModManip', u'solidFractal', u'spBirailSrf', u'sphericalProjManip',
                   u'spotCylinderManip', u'spotLight', u'spotManip', u'spring', u'squareSrf', u'squareSrfManip',
                   u'stencil', u'stereoRigCamera', u'stitchAsNurbsShell', u'stitchSrf', u'stitchSrfManip', u'stroke',
                   u'strokeGlobals', u'stucco', u'studioClearCoat', u'styleCurve', u'subCurve', u'subSurface',
                   u'subdAddTopology', u'subdAutoProj', u'subdBlindData', u'subdCleanTopology', u'subdHierBlind',
                   u'subdLayoutUV', u'subdMapCut', u'subdMapSewMove', u'subdMappingManip', u'subdPlanarProj',
                   u'subdProjManip', u'subdTweak', u'subdTweakUV', u'subdiv', u'subdivCollapse', u'subdivComponentId',
                   u'subdivReverseFaces', u'subdivSurfaceVarGroup', u'subdivToNurbs', u'subdivToPoly', u'substance',
                   u'substanceOutput', u'surfaceEdManip', u'surfaceInfo', u'surfaceLuminance', u'surfaceShader',
                   u'surfaceVarGroup', u'symmetryConstraint', u'tangentConstraint', u'texLattice',
                   u'texLatticeDeformManip', u'texMoveShellManip', u'texSmoothManip', u'texSmudgeUVManip',
                   u'textButtonManip', u'textManip2D', u'texture3dManip', u'textureBakeSet', u'textureDeformer',
                   u'textureDeformerHandle', u'textureToGeom', u'time', u'timeFunction', u'timeToUnitConversion',
                   u'timeWarp', u'toggleManip', u'toggleOnLineManip', u'toolDrawManip', u'toolDrawManip2D',
                   u'toonLineAttributes', u'towPointOnCurveManip', u'towPointOnSurfaceManip', u'trackInfoManager',
                   u'trans2dManip', u'transUV2dManip', u'transferAttributes', u'transform', u'transformGeometry',
                   u'translateLimitsManip', u'translateManip', u'translateUVManip', u'transposeMatrix', u'trim',
                   u'trimManip', u'trimWithBoundaries', u'triplanarProjManip', u'tripleShadingSwitch',
                   u'trsInsertManip', u'trsManip', u'turbulenceField', u'turbulenceManip', u'tweak', u'uniformField',
                   u'unitConversion', u'unitToTimeConversion', u'unknown', u'unknownDag', u'unknownTransform',
                   u'untrim', u'useBackground', u'uv2dManip', u'uvChooser', u'vectorProduct', u'vectorRenderGlobals',
                   u'vertexBakeSet', u'viewColorManager', u'volumeAxisField', u'volumeBindManip', u'volumeFog',
                   u'volumeLight', u'volumeNoise', u'volumeShader', u'vortexField', u'water', u'weightGeometryFilter',
                   u'wire', u'wood', u'wrap', u'writeToColorBuffer', u'writeToDepthBuffer', u'writeToLabelBuffer',
                   u'writeToVectorBuffer', u'wtAddMatrix', u'xformManip', u'xgmArchiveGuide', u'xgmCardGuide',
                   u'xgmConnectivity', u'xgmDescription', u'xgmGuide', u'xgmGuideManip', u'xgmGuideSculptManip',
                   u'xgmMakeGuide', u'xgmNurbsPatch', u'xgmPalette', u'xgmPatch', u'xgmPointsManip', u'xgmPointsViewer',
                   u'xgmSphereGuide', u'xgmSplineGuide', u'xgmSubdPatch']

for node in _ABSTRACT_NODES:
    print "class %s (LSByType):\n    TYPE='%s'" % (node, node)